[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://euro-asia-vent.netlify.app"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs" 